language: objective-c
osx_image: xcode7.2
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - PROJECT=AlamofireNetworkActivityIndicator.xcodeproj
  - IOS_FRAMEWORK_SCHEME="AlamofireNetworkActivityIndicator"
  - IOS_SDK=iphonesimulator9.2
  matrix:
    - DESTINATION="OS=8.1,name=iPhone 4S"       SCHEME="$IOS_FRAMEWORK_SCHEME"  SDK="$IOS_SDK"  POD_LINT="NO"
    - DESTINATION="OS=8.2,name=iPhone 5"        SCHEME="$IOS_FRAMEWORK_SCHEME"  SDK="$IOS_SDK"  POD_LINT="NO"
    - DESTINATION="OS=8.3,name=iPhone 5S"       SCHEME="$IOS_FRAMEWORK_SCHEME"  SDK="$IOS_SDK"  POD_LINT="NO"
    - DESTINATION="OS=8.4,name=iPhone 6"        SCHEME="$IOS_FRAMEWORK_SCHEME"  SDK="$IOS_SDK"  POD_LINT="NO"
    - DESTINATION="OS=9.0,name=iPhone 6 Plus"   SCHEME="$IOS_FRAMEWORK_SCHEME"  SDK="$IOS_SDK"  POD_LINT="NO"
    - DESTINATION="OS=9.1,name=iPhone 6S"       SCHEME="$IOS_FRAMEWORK_SCHEME"  SDK="$IOS_SDK"  POD_LINT="NO"
    - DESTINATION="OS=9.2,name=iPhone 6S Plus"  SCHEME="$IOS_FRAMEWORK_SCHEME"  SDK="$IOS_SDK"  POD_LINT="NO"
before_install:
  - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
  - set -o pipefail
  - git submodule update --init --recursive
  - xcodebuild -version
  - xcodebuild -showsdks

  # Build Framework in Debug and Run Tests
  - xcodebuild -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c;
  
  # Build Framework in Release and Run Tests  
  - xcodebuild -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration ReleaseTest ONLY_ACTIVE_ARCH=NO test | xcpretty -c;

  # Run `pod lib lint` if specified
  - if [ $POD_LINT == "YES" ]; then
      pod repo update master;
      pod lib lint;
    fi
